create table if not exists public.members (
  id bigint generated by default as identity primary key,
  email text not null unique,
  password_hash text not null,
  created_at timestamptz not null default now()
);

alter table public.members enable row level security;
create table if not exists public.cart_items (
  id bigint generated by default as identity primary key,
  member_id bigint not null references public.members(id) on delete cascade,
  product_id bigint not null references public.products(id) on delete cascade,
  quantity integer not null default 1 check (quantity > 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(member_id, product_id)
);

alter table public.cart_items enable row level security;

