create table if not exists public.members (
  id bigint generated by default as identity primary key,
  email text not null unique,
  password_hash text not null,
  created_at timestamptz not null default now()
);

alter table public.members enable row level security;
create table if not exists public.cart_items (
  id bigint generated by default as identity primary key,
  member_id bigint not null references public.members(id) on delete cascade,
  product_id bigint not null references public.products(id) on delete cascade,
  quantity integer not null default 1 check (quantity > 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(member_id, product_id)
);

alter table public.cart_items enable row level security;
create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  member_id bigint not null references public.members(id) on delete cascade,
  status text not null default 'pending_payment',
  total_amount integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  product_id bigint not null references public.products(id),
  quantity integer not null check (quantity > 0),
  unit_price integer not null default 0,
  line_total integer not null default 0,
  created_at timestamptz not null default now()
);

alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.orders
alter column status set default 'pending_payment';

alter table public.orders
add constraint orders_status_check
check (status in (
  'pending_payment',
  'paid',
  'processing',
  'shipped',
  'completed',
  'cancelled',
  'payment_failed'
));

