create table if not exists public.members (
  id bigint generated by default as identity primary key,
  email text not null unique,
  password_hash text not null,
  created_at timestamptz not null default now()
);

alter table public.members enable row level security;
